if(NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "module_release_targets_test.cmake requires PROJECT_SOURCE_DIR")
endif()

file(GLOB_RECURSE manifests LIST_DIRECTORIES FALSE
    "${PROJECT_SOURCE_DIR}/modules/*/lode.json")

foreach(manifest_path IN LISTS manifests)
    file(READ "${manifest_path}" manifest)
    string(JSON libraries_type ERROR_VARIABLE libraries_error TYPE "${manifest}" libraries)
    if(libraries_error)
        continue()
    endif()
    if(NOT libraries_type STREQUAL "OBJECT")
        message(FATAL_ERROR "Native module manifest has a non-object libraries field: ${manifest_path}")
    endif()

    string(JSON target_count ERROR_VARIABLE targets_error LENGTH "${manifest}" releaseTargets)
    if(targets_error OR target_count LESS 1)
        message(FATAL_ERROR "Native module manifest must declare releaseTargets: ${manifest_path}")
    endif()

    set(has_windows_x64 FALSE)
    math(EXPR final_target "${target_count} - 1")
    foreach(target_index RANGE ${final_target})
        string(JSON platform GET "${manifest}" releaseTargets ${target_index} platform)
        string(JSON architecture GET "${manifest}" releaseTargets ${target_index} architecture)
        if(platform STREQUAL "windows" AND architecture STREQUAL "x64")
            set(has_windows_x64 TRUE)
        endif()
    endforeach()
    if(NOT has_windows_x64)
        message(FATAL_ERROR "Native module must publish the implemented windows/x64 target: ${manifest_path}")
    endif()
endforeach()
